### ISSUE TITLE
[FEATURE] Set up Travis CI and Jenkins CI/CD

### ISSUE THREAD

**Issue by kingsley-einstein** [BuildForSDGCohort2/Team-030-Backend#13]
Connect Travis CI to this repository and also update the Jenkinsfile for Jenkins pipeline builds. Either of both CI tool could be leveraged for deployment based on the success state of edge case tests. Jenkins might require an extra tweaking to deploy to a cloud service provider (say Heroku or Kintohub). Travis on the other hand makes it easier to deploy to Heroku using specific key value pair in the .travis.yml file which would require tweaking if we were to opt for a different cloud service provider.

**Comment by jan-far** [comment]
We go with TravisCI. I think that will be better.

**Comment by jan-far** [comment]
Thanks. issue solved
