### ISSUE TITLE
User(Farmer) Schema and API router [POST]

### ISSUE THREAD

**Issue by IdamEniIdam** [BuildForSDGCohort2/Team-030-Backend#22]
Farmers will register with some information and then login with their email and password.
same email can't be used twice.
passport-jwt, jsonwebtoken, passport, bcryptjs. MongoDB Database, more features to be added

**Comment by jan-far** [comment]
Okay, will review. Thanks. I'm working on the db

**Comment by kingsley-einstein** [comment]
No need for passport. We could create our own authentication middleware.

**Comment by kingsley-einstein** [comment]
The goal is to have control over all application concerns. Writing our own authentication middleware ensures auth process is carried out as we desire.

**Comment by josiaharkson** [comment]
I agree with @kingsley-einstein  no need for passport. Creaing our own auth middleware gives us more control.

**Comment by IdamEniIdam** [comment]
But have you gone through the code @kingsley-einstein
