### ISSUE TITLE
[FEATURE] User Authentication

### ISSUE THREAD

**Issue by jan-far** [BuildForSDGCohort2/Team-030-Backend#27]
Create the authentication middleware file to verify users

**Comment by kingsley-einstein** [comment]
I have created a user schema and a helper class with methods to aid in signing and decoding tokens. The middleware would modify the request, appending the decoded payload to it provided it isn't malformed or expired. A session ID field is also included in the payload which would be checked against a sessions collection. If the ID matches any entity in the collection, it is thus assumed the user has signed out, terminating that session.

**Comment by jan-far** [comment]
Make a PR. Ork needs to be done. Just curious as to why sone of us are mute. Aside the 4 active on github.
PR your codes! Well done bro
